name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm i
      - name: Install backend dependencies
        run: |
          cd backend
          npm i
      - name: Run dev front
        run: |
          cd frontend
          npm run dev-front
      - name: Run dev back
        run: |
          cd backend
          npm run dev-back
      - name: Cypress run
        uses: cypress-io/github-action@v6