name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: install dependencies
      - run: npm i 

      - name: run dev front
      - run: npm run dev-front

      - name: run dev back
      - run: npm run dev-back

      - name: Cypress run
        uses: cypress-io/github-action@v6
        